
import "./globals.css";

export const metadata = {
  title: "Swabi Laundry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={className}>{children}</body>
    </html>
  );
}
